name: .NET Package and Release

on:
  push:
    branches:
      - "pack*"
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true

      - name: UPX version
        run: upx --version

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Packaging
        run: dotnet publish LotteryProgram\LotteryProgram.csproj --configuration Release --output .\dist

      - name: Minimize Executables with UPX
        run: upx -fq -7 dist\*.exe

      - name: Compress Artifacts
        run: Compress-Archive -Path dist\* -Destination lottery.zip

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "lottery.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
